import QuestionExtras from "./ui/QuestionExtras";

const DISCLAIMER =
  "This suggestion is generated from previous question patterns and AI analysis. It does not guarantee actual exam questions.";

function getText(value, fallback = "-") {
  if (value === null || value === undefined) {
    return fallback;
  }

  const text = String(value).trim();
  return text || fallback;
}

function getQuestionText(item) {
  return item?.question || item?.question_text || item?.text || item?.title || item?.prompt || item?.suggestion || "Suggested question";
}

function getMarks(item) {
  return item?.marks ?? item?.total_marks ?? item?.expected_marks ?? "-";
}

function getScore(item) {
  const rawScore = Number(item?.importance ?? item?.probability_score ?? item?.prediction_score ?? item?.importance_score ?? item?.score ?? item?.confidence ?? item?.probability ?? item?.frequency);
  if (!Number.isFinite(rawScore)) {
    return "-";
  }

  const normalizedScore = rawScore <= 1 ? rawScore * 100 : rawScore;
  return `${normalizedScore.toFixed(1)}%`;
}

function formatDateTime(value) {
  const date = value ? new Date(value) : new Date();
  if (Number.isNaN(date.getTime())) {
    return getText(value);
  }

  return new Intl.DateTimeFormat("en-GB", {
    dateStyle: "medium",
    timeStyle: "short",
    timeZone: "Asia/Dhaka",
  }).format(date);
}

function getYears(item) {
  if (Array.isArray(item?.source_years) && item.source_years.length > 0) {
    return item.source_years.join(", ");
  }

  return getText(item?.exam_year, "Unknown");
}

function SuggestionReportPreview({ reportData, suggestions }) {
  if (!reportData || suggestions.length === 0) {
    return null;
  }

  const repeatedTopics = Array.isArray(reportData.most_repeated_topics) ? reportData.most_repeated_topics : [];
  const subjectCode = getText(reportData.subject_code);
  const subjectName = getText(reportData.subject_name, "Unknown Subject");
  const retrievalSource = getText(reportData.retrieval_source || reportData.diagnostics?.retrieval_source);
  const mode = getText(reportData.mode, reportData.fallback_used ? "Published history fallback" : "Semantic search");

  return (
    <section className="print-report-root mt-6 bg-white text-slate-950 shadow-sm shadow-slate-200/70 print:mt-0 print:shadow-none">
      <div className="report-page mx-auto max-w-5xl rounded-none border border-slate-200 bg-white p-6 sm:p-8 print:max-w-none print:border-0 print:p-0">
        <header className="report-section border-b border-slate-200 pb-5">
          <p className="text-sm font-bold uppercase tracking-[0.18em] text-indigo-700">FakiBuzz</p>
          <div className="mt-2 flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between">
            <div>
              <h1 className="text-3xl font-bold tracking-normal text-slate-950">Suggestion Report</h1>
              <p className="mt-1 text-sm font-medium text-slate-500">AI-assisted exam preparation report</p>
            </div>
            <p className="text-sm font-medium text-slate-600">Generated by FakiBuzz</p>
          </div>
        </header>

        <section className="report-section mt-6 grid gap-3 rounded-lg border border-slate-200 bg-slate-50 p-4 sm:grid-cols-2 lg:grid-cols-3">
          <InfoItem label="Subject Code" value={subjectCode} />
          <InfoItem label="Subject Name" value={subjectName} />
          <InfoItem label="Generated" value={formatDateTime(reportData.generated_at)} />
          <InfoItem label="Query" value={getText(reportData.query)} className="lg:col-span-2" />
          <InfoItem label="Retrieval Source" value={retrievalSource} />
          <InfoItem label="Suggestion Mode" value={mode} />
        </section>

        <section className="report-section mt-5 rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-950">
          <span className="font-semibold">Disclaimer: </span>
          {DISCLAIMER}
        </section>

        <section className="report-section mt-7">
          <h2 className="text-xl font-bold text-slate-950">Most Repeated Topics</h2>
          <div className="mt-3 overflow-hidden rounded-lg border border-slate-200">
            <table className="w-full border-collapse text-left text-sm">
              <thead className="bg-slate-100 text-xs uppercase tracking-[0.12em] text-slate-500">
                <tr>
                  <th className="px-3 py-2 font-bold">Topic</th>
                  <th className="px-3 py-2 font-bold">Frequency</th>
                  <th className="px-3 py-2 font-bold">Years</th>
                  <th className="px-3 py-2 font-bold">Importance</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-200 bg-white">
                {repeatedTopics.length > 0 ? (
                  repeatedTopics.map((topic, index) => (
                    <tr key={`${topic.topic || "topic"}-${index}`}>
                      <td className="px-3 py-2 font-semibold text-slate-900">{getText(topic.topic)}</td>
                      <td className="px-3 py-2 text-slate-700">{getText(topic.frequency)}</td>
                      <td className="px-3 py-2 text-slate-700">{Array.isArray(topic.years) && topic.years.length > 0 ? topic.years.join(", ") : "-"}</td>
                      <td className="px-3 py-2 text-slate-700">{getText(topic.importance_score ?? topic.probability)}</td>
                    </tr>
                  ))
                ) : (
                  <tr>
                    <td className="px-3 py-3 text-slate-600" colSpan={4}>No repeated topics available.</td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
        </section>

        <section className="report-section mt-7">
          <h2 className="text-xl font-bold text-slate-950">Suggested Questions</h2>
          <div className="mt-4 space-y-4">
            {suggestions.map((item, index) => (
              <article className="report-question-card rounded-lg border border-slate-200 bg-white p-4" key={item.id || `${item.question_no || "suggestion"}-${index}`}>
                <div className="flex flex-col gap-2 border-b border-slate-100 pb-3 sm:flex-row sm:items-start sm:justify-between">
                  <div>
                    <p className="text-xs font-bold uppercase tracking-[0.14em] text-indigo-700">Suggestion {item.suggestion_no || index + 1}</p>
                    <h3 className="mt-2 whitespace-pre-line text-base font-bold leading-7 text-slate-950">{getQuestionText(item)}</h3>
                  </div>
                  <span className="inline-flex self-start rounded-full bg-indigo-50 px-3 py-1 text-xs font-bold text-indigo-700">Score: {getScore(item)}</span>
                </div>

                <div className="mt-3 grid gap-2 text-sm text-slate-700 sm:grid-cols-3">
                  <p><span className="font-semibold text-slate-950">Topic:</span> {getText(item.topic || item.final_topic || item.suggested_topic, "No topic")}</p>
                  <p><span className="font-semibold text-slate-950">Year:</span> {getYears(item)}</p>
                  <p><span className="font-semibold text-slate-950">Marks:</span> {getText(getMarks(item))}</p>
                </div>

                <QuestionExtras item={item} className="report-question-extras" formulaLabel="Formula / Math" />

                {item.reason && (
                  <p className="mt-3 rounded-lg bg-slate-50 px-3 py-2 text-sm leading-6 text-slate-700">
                    <span className="font-semibold text-slate-950">Reason:</span> {item.reason}
                  </p>
                )}
              </article>
            ))}
          </div>
        </section>

        <footer className="report-footer mt-8 border-t border-slate-200 pt-4 text-center text-xs font-medium text-slate-500">
          Generated by FakiBuzz | fakibuzz.me
        </footer>
      </div>
    </section>
  );
}

function InfoItem({ label, value, className = "" }) {
  return (
    <div className={`min-w-0 ${className}`}>
      <p className="text-xs font-bold uppercase tracking-[0.12em] text-slate-500">{label}</p>
      <p className="mt-1 break-words text-sm font-semibold text-slate-950">{value}</p>
    </div>
  );
}

export default SuggestionReportPreview;
